DESTIDIR?=	/usr/local/libexec/nagios
RUBY?=	/usr/local/bin/ruby

all:	check_nsca

check_nsca:
	sed -e "s|__RUBY__|${RUBY}|" check_nsca.rb > ${.TARGET} || rm ${.TARGET}

install:
	install check_nsca ${DESTDIR}/

clean:
	rm -f check_nsca
